name: JumpSetup
author: Nico_ND1
version: ${project.version}
main: de.valuga.jump.setup.bukkit.JumpSetupPlugin

commands:
    jumpsetup:
        permission: jump.commands.setup
        aliases: [jumpandrunsetup]
